# Generated by Django 4.1.1 on 2022-11-02 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_alter_comment_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
