# Generated by Django 4.1.1 on 2022-11-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
