# Generated by Django 4.1.1 on 2022-11-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0005_remove_comment_post_alter_comment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
