# Generated by Django 4.1.1 on 2022-11-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
