# Generated by Django 4.1.1 on 2022-11-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0008_alter_comment_table_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
