# Generated by Django 4.1 on 2022-10-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mensajeria', '0002_emisor_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emisor',
            old_name='usuario',
            new_name='user',
        ),
    ]
