# Generated by Django 4.1 on 2022-10-08 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Mensajeria', '0003_rename_usuario_emisor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emisor',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='emisor',
            name='mensaje',
            field=models.CharField(max_length=10000),
        ),
        migrations.CreateModel(
            name='receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=10000)),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
