# Generated by Django 4.1 on 2022-10-10 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Mensajeria', '0004_rename_user_emisor_usuario_alter_emisor_mensaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canalmensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ManyToManyField(related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
