# Generated by Django 4.1 on 2022-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mensajeria', '0006_remove_canalmensajes_usuario_canalmensajes_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisor',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
