# Generated by Django 4.1 on 2022-09-28 00:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField(max_length=200)),
                ('subtitulo', ckeditor.fields.RichTextField(max_length=200)),
                ('cuerpo', ckeditor.fields.RichTextField(max_length=200)),
                ('autor', ckeditor.fields.RichTextField(max_length=200)),
                ('fecha', ckeditor.fields.RichTextField(max_length=200)),
                ('imagen', ckeditor.fields.RichTextField(max_length=200)),
            ],
        ),
    ]
