# Generated by Django 4.1.1 on 2022-10-03 16:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Tienda', '0003_nuestrasoficinas_sobrenosotros_delete_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuestrasoficinas',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
