# Generated by Django 4.1 on 2022-10-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0004_alter_nuestrasoficinas_cuerpo_alter_servicios_cuerpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
