# Generated by Django 4.1 on 2022-10-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0005_alter_servicios_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
