# Generated by Django 4.1.1 on 2022-10-18 15:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField(max_length=20000)),
                ('subtitulo', ckeditor.fields.RichTextField(max_length=20000)),
                ('cuerpo', ckeditor.fields.RichTextField(max_length=200000)),
                ('autor', ckeditor.fields.RichTextField(max_length=2000)),
                ('imagen', ckeditor.fields.RichTextField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField(max_length=200000)),
                ('subtitulo', ckeditor.fields.RichTextField(max_length=200000)),
                ('cuerpo', ckeditor.fields.RichTextField(max_length=200000)),
                ('autor', ckeditor.fields.RichTextField(max_length=2000)),
                ('imagen', ckeditor.fields.RichTextField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField(max_length=200000)),
                ('subtitulo', ckeditor.fields.RichTextField(max_length=200000)),
                ('cuerpo', ckeditor.fields.RichTextField(max_length=200000000)),
                ('autor', ckeditor.fields.RichTextField(max_length=20000)),
                ('imagen', ckeditor.fields.RichTextField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
