# Generated by Django 4.1 on 2022-10-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0006_delete_clientes_delete_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuestrasoficinas',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
