# Generated by Django 4.1.1 on 2022-10-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0006_nosotros_oficinas_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientes',
        ),
        migrations.DeleteModel(
            name='NuestrasOficinas',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='servicios',
        ),
        migrations.DeleteModel(
            name='SobreNosotros',
        ),
    ]
