# Generated by Django 4.1.1 on 2022-10-19 00:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0007_delete_clientes_delete_nuestrasoficinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='imagen',
            field=ckeditor.fields.RichTextField(max_length=20000000),
        ),
        migrations.AlterField(
            model_name='oficinas',
            name='imagen',
            field=ckeditor.fields.RichTextField(max_length=2000000),
        ),
        migrations.AlterField(
            model_name='services',
            name='imagen',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
    ]
