# Generated by Django 4.1 on 2022-10-14 22:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0007_alter_nuestrasoficinas_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='nuestrasoficinas',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='nuestrasoficinas',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='nuestrasoficinas',
            name='titulo',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=200000000),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='titulo',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
