# Generated by Django 4.1 on 2022-10-16 02:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0008_alter_avatar_imagen_alter_nuestrasoficinas_cuerpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrenosotros',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(max_length=200000),
        ),
    ]
