# Generated by Django 4.1 on 2022-10-16 06:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0009_alter_sobrenosotros_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', ckeditor.fields.RichTextField(max_length=200)),
                ('subtitulo', ckeditor.fields.RichTextField(max_length=20000)),
                ('cuerpo', ckeditor.fields.RichTextField(max_length=200000)),
                ('autor', ckeditor.fields.RichTextField(max_length=2000)),
                ('imagen', ckeditor.fields.RichTextField(max_length=200)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='SobreNosotros',
        ),
        migrations.AlterField(
            model_name='nuestrasoficinas',
            name='autor',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='autor',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
