# Generated by Django 4.1 on 2022-10-16 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda', '0012_oficinas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuestrasOficinas',
        ),
        migrations.DeleteModel(
            name='servicios',
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='titulo',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
